import { Sparkles } from "lucide-react";
import type { AiInsights } from "../types";

interface Props {
  insights?: AiInsights;
}

export function AiBriefing({ insights }: Props) {
  const lines = (insights?.briefing ?? "")
    .split("\n")
    .map((l) => l.replace(/^[-*]\s*/, "").trim())
    .filter(Boolean);

  const generatedAt = insights?.generatedAt
    ? new Date(insights.generatedAt).toLocaleString("en-US", {
        month: "short",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      })
    : null;

  return (
    <div className="bg-gradient-to-br from-indigo-500/10 to-slate-800/50 border border-indigo-500/30 rounded-xl p-5 h-full">
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <Sparkles size={15} className="text-indigo-300" />
          <h2 className="text-sm font-semibold text-slate-100">AI Daily Briefing</h2>
        </div>
        {generatedAt && (
          <span className="text-[11px] text-slate-500">Generated {generatedAt}</span>
        )}
      </div>

      {lines.length > 0 ? (
        <ul className="space-y-2">
          {lines.map((line, i) => (
            <li key={i} className="flex items-start gap-2.5">
              <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-indigo-400 shrink-0" />
              <p className="text-xs text-slate-300 leading-relaxed">{line}</p>
            </li>
          ))}
        </ul>
      ) : (
        <p className="text-xs text-slate-500 leading-relaxed">
          The AI briefing will appear here after the next scheduled run (n8n + OpenAI).
        </p>
      )}

      <p className="text-[11px] text-slate-600 mt-4 pt-3 border-t border-slate-700/50">
        Generated by an n8n AI Agent from the day's Telegram activity.
      </p>
    </div>
  );
}
